version: '3'
services:
  redis:
    image: redis
    restart: always
    volumes:
      - redis:/data
  mysql:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: superset
      MYSQL_DATABASE: superset
      MYSQL_USER: superset
      MYSQL_PASSWORD: superset
    volumes:
      - mysql:/var/lib/mysql
  superset:
    image: docker-superset:latest
    restart: always
    depends_on:
      - mysql
      - redis
    environment:
      MAPBOX_API_KEY: ${MAPBOX_API_KEY}
      SUPERSET_DB: 'mysql://superset:superset@mysql:3306/superset'
      REDIS_HOST: 'redis'
    ports:
      - "8088:8088"
  worker:
    image: docker-superset:latest
    restart: always
    depends_on:
      - mysql
      - redis
    environment:
      MAPBOX_API_KEY: ${MAPBOX_API_KEY}
      SUPERSET_DB: 'mysql://superset:superset@mysql:3306/superset'
      REDIS_HOST: 'redis'
    command: celery worker --app=superset.sql_lab:celery_app --pool=gevent -Ofair

volumes:
  mysql:
    external: false
  redis:
    external: false
